# Generated by Django 4.2.4 on 2023-08-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='search_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='operator_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
