# Generated by Django 4.2.4 on 2023-08-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_remove_dashboard_search_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='search_serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
