# Generated by Django 4.2.4 on 2023-08-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_dashboard_search_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='search_serial_number',
        ),
    ]
