# Generated by Django 4.2.4 on 2023-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_remove_dashboard_search_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='serial_number',
            new_name='work_order',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='gap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
